language: node_js
node_js:
  - "12"
  - "10"
  - "8"
script:
  - npm run lint
  - npm run build
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libudev-dev
before_install:
  - wget https://github.com/OpenZWave/open-zwave/archive/master.zip
  - unzip master.zip
  - cd open-zwave-master
  - sudo make install
  - sudo ldconfig /usr/local/lib /usr/local/lib64
  - npm install -g node-gyp
  - cd ..