name: ci

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: Install Deps
      run: sudo apt-get install libudev-dev
    - name: Checkout Openzwave
      uses: actions/checkout@v2
      with:
        repository: OpenZWave/open-zwave
        path: open-zwave
    - name: Install Openzwave
      run: |
        cd open-zwave
        sudo make install
        sudo ldconfig /usr/local/lib /usr/local/lib64
        cd ..
        rm -rf open-zwave

    - name: Checkout Zwave2Mqtt
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install - Build - Lint - Test
      run: |
        npm install
        npm run lint
        npm run build
        npm run test

    - name: Generate coverage report
      if: matrix['node-version'] == '12.x'
      run: |
        npm run coverage
        npm run record-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: matrix['node-version'] == '12.x'
      with:
        github-token: ${{ secrets.github_token }}