name: Docker Build

on:
  push:
  #   branches:
  #     - master
  # pull_request:
  # release:
  #   types:
  #     - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo foo >> ./TAGS
          echo bar >> ./TAGS

          TAGS=$(cat TAGS)
          TAGS="${TAGS//'%'/'%25'}"
          TAGS="${TAGS//$'\n'/'%0A'}"
          TAGS="${TAGS//$'\r'/'%0D'}"
          # echo TAGS=$TAGS >> $GITHUB_ENV

          echo ::set-output name=TAGS::${TAGS}

      - run: |
          echo start
          echo ${{ steps.prepare.outputs.TAGS }}
          echo end

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - name: build+push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          tags: |
            ${{ steps.prepare.outputs.TAGS }}
