name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        run: |
          DOCKER_REPO=robertslando/zwave2mqtt
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            TAGS="${DOCKER_REPO}:dev\n"
          fi
          if [ "$GITHUB_EVENT_NAME" == "release" ]; then
            TAGS="${TAGS}${DOCKER_REPO}:latest\n"
            TAGS="${TAGS}${DOCKER_REPO}:$(echo ${GITHUB_REF} | sed "s/refs\/tags\/v//")\n"
          fi

          TAGS="${TAGS}${DOCKER_REPO}:sha-${GITHUB_SHA}"

          echo TAGS="${TAGS}" >> $GITHUB_ENV
          echo DOCKER_REPO="${DOCKER_REPO}" >> $GITHUB_ENV

      - name: build+push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:sha-${{ env.GITHUB_SHA }}
          platforms: linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.TAGS }}
