name: Trigger Docker Build

on:
  push:
    branches: 
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Repository Dispatch
         uses: peter-evans/repository-dispatch@v1
         with:
           token: ${{ secrets.DOCKER_REPO_TOKEN }}
           repository: robertsLando/Zwave2Mqtt-docker
           event-type: build
