name: Docker Build

on:
  push:
  #   branches:
  #     - master
  # pull_request:
  # release:
  #   types:
  #     - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          DOCKER_REPO=robertslando/zwave2mqtt
          echo ${DOCKER_REPO}:sha-${GITHUB_SHA} > ./TAGS

          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            echo ${DOCKER_REPO}:dev >> ./TAGS
          fi
          if [ "$GITHUB_EVENT_NAME" == "release" ]; then
            echo ${DOCKER_REPO}:latest >> ./TAGS
            echo ${DOCKER_REPO}:$(echo ${GITHUB_REF} | sed "s/refs\/tags\/v//")\n") >> ./TAGS
          fi

          TAGS=$(cat TAGS)"
          TAGS="${TAGS//'%'/'%25'}"
          TAGS="${TAGS//$'\n'/'%0A'}"
          TAGS="${TAGS//$'\r'/'%0D'}"
          echo ::set-output name=TAGS::${TAGS}
          echo DOCKER_REPO="${DOCKER_REPO}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - name: build+push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          tags: |
            ${{ steps.prepare.outputs.TAGS }}
