name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Just build on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: docker build .

      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: crazy-max/ghaction-docker-buildx@v1
        if: ${{ github.event_name != 'pull_request' }}

      - name: Dev
        if: ${{ github.ref == 'git/refs/heads/master'}}
        run: |
          docker buildx build \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
          -t ${GITHUB_REPOSITORY}:latest \
          --push \
          .

      - name: Latest
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
          -t ${GITHUB_REPOSITORY}:latest \
          --push \
          .

      - name: Tag
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
          -t ${GITHUB_REPOSITORY}:$(echo ${GITHUB_REF} | sed "s/git\/refs\/tags\/v//") \
          --push \
          .
