name: Docker Build

on:
  push:
  #   branches:
  #     - master
  # pull_request:
  # release:
  #   types:
  #     - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          DOCKER_REPO=robertslando/zwave2mqtt

          TAGS=${DOCKER_REPO}:sha-${GITHUB_SHA}

          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            TAGS=$TAGS,${DOCKER_REPO}:dev
          fi
          if [ "$GITHUB_EVENT_NAME" == "release" ]; then
            TAGS=$TAGS,${DOCKER_REPO}:latest
            TAGS=$TAGS,${DOCKER_REPO}:$(echo ${GITHUB_REF} | sed "s/refs\/tags\/v//") >> ./TAGS
          fi
          echo $TAGS >> $GITHUB_ENV
          echo DOCKER_REPO="${DOCKER_REPO}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1

      - name: build+push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          tags: ${{ env.TAGS }}
