name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prepare
        run: |
          echo foo > ./TAGS
          echo bar > ./TAGS

          TAGS=$(cat TAGS)
          TAGS="${TAGS//'%'/'%25'}"
          TAGS="${TAGS//$'\n'/'%0A'}"
          TAGS="${TAGS//$'\r'/'%0D'}"
          echo TAGS=$TAGS >> $GITHUB_ENV
          echo "::set-output name=TAGS::${$TAGS}"

      - run: |
          echo ${{ steps.prepare.outputs.TAGS }}
          echo next
          echo $TAGS
