name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v1

      - name: Just build on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker buildx build \
          -f docker/Dockerfile \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7 \
          -t robertslando/zwave2mqtt:dev \
          .

      - name: Login to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: crazy-max/ghaction-docker-buildx@v1
        if: ${{ github.event_name != 'pull_request' }}

      - name: Dev
        if: ${{ github.ref == 'refs/heads/master'}}
        run: |
          docker buildx build \
          -f docker/Dockerfile \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7 \
          -t robertslando/zwave2mqtt:dev \
          --push \
          .

      - name: Latest & tag
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build \
          -f docker/Dockerfile \
          --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7 \
          -t robertslando/zwave2mqtt:$(echo ${GITHUB_REF} | sed "s/refs\/tags\/v//") \
          -t robertslando/zwave2mqtt:latest \
          --push \
          .
