# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Install Deps
      run: sudo apt-get install libudev-dev
    - name: Checkout Openzwave
      uses: actions/checkout@v2
      with:
        repository: OpenZWave/open-zwave
        path: open-zwave
    - name: Install Openzwave
    - run: |
        cd open-zwave
        sudo make install
        sudo ldconfig /usr/local/lib /usr/local/lib64
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm lint
        npm run build
